name: sipenak_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  awesome_dialog: ^2.1.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0
  connectivity_plus: ^1.0.5
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.0
  division: ^0.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.20.0-nullsafety.3
  http: ^0.13.3
  image_picker: ^0.8.0+3
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  searchable_dropdown: ^1.1.3
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  pinch_zoom_image_updated: ^0.2.6
  provider: ^4.3.2+3
  url_launcher: ^6.0.9
  whatsapp_unilink: ^2.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
        - asset: assets/fonts/muli/Muli-Light.ttf
